# Generated by Django 6.1.1 on 2026-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
