# Generated by Django 6.1.1 on 2026-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_education_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="ended_at",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="started_at",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="experience",
            name="ended_at",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="started_at",
            field=models.IntegerField(),
        ),
    ]
